=== DrewMcNair/GHEDesigner/ghedesigner/schemas/file_structure.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "topology": {
      "type": "array",
      "description": "A list of name/type map objects that define the system topology."
    },
    "fluid": {
      "type": "object",
      "description": "A fluid definition object."
    },
    "building": {
      "type": "object",
      "description": "A map of available building definition objects."
    },
    "ground-heat-exchanger": {
      "type": "object",
      "description": "A collection of objects that define a ground heat exchanger system."
    },
    "pump": {
      "type": "object",
      "description": ""
    },
    "towers": {
      "type": "object",
      "description": ""
    },
    "generic-loads": {
      "type": "object",
      "description": ""
    },
    "simulation-control": {
      "type": "object",
      "description": ""
    },
    "version": {
      "type": "number",
      "description": "An integer version ID for this input structure, for future-proofing."
    }
  },
  "required": [
    "topology",
    "fluid",
    "ground-heat-exchanger",
    "simulation-control",
    "version"
  ]
}

=== DrewMcNair/GHEDesigner/demos/run_simulation_presized.json
{
  "version": 1,
  "topology": [
    { "type": "building", "name": "building1" },
    { "type": "ground-heat-exchanger", "name": "ghe1" }
  ],
  "fluid": {
    "fluid_name": "WATER",
    "concentration_percent": 0,
    "temperature": 20
  },
  "building": {
    "building1": {
      "name": "load 1",
      "loads": "test_data/test_bldg_loads.csv",
      "cop": 3,
      "capacity": "AUTOSIZE"
    }
  },
  "ground-heat-exchanger": {
    "ghe1": {
      "do-sizing": false,
      "grout": {
        "conductivity": 1,
        "rho_cp": 3901000
      },
      "soil": {
        "conductivity": 2,
        "rho_cp": 2343493,
        "undisturbed_temp": 18.3
      },
      "pipe": {
        "inner_diameter": 0.03404,
        "outer_diameter": 0.04216,
        "shank_spacing": 0.01856,
        "roughness": 0.000001,
        "conductivity": 0.4,
        "rho_cp": 1542000,
        "arrangement": "SINGLEUTUBE"
      },
      "borehole": {
        "buried_depth": 2,
        "diameter": 0.14
      },
      "pre_designed": {
        "H": 150,
        "x": [0.0],
        "y": [0.0]
      }
    }
  },
  "simulation-control": {
    "thermal-sizing-run": true,
    "hourly-run": true,
    "hydraulic-run": true,
    "simulation-months": 240
  }
}
